config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :clients

  resources :clients do
    resources :orders
  end

  get '/get_inventory', to: 'inventories#get_inventory'


  resources :inventories
  resources :shipments
  resources :about

  devise_for :users

  #GET routes

  get '/distance', to: 'shipments#distance'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :orders
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :client
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def create
    client = Client.new(client_params)
    if client.save
      render json: client
    end
  end

  def destroy
    if Client.find(params[:id]).destroy
      render json: { id: params[:id].to_i }
    end
  end

  private

  def client_params
    params.require(:client).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
  end
  
  def get_inventory
    @inventories = Inventory.all
      render json: @inventories
  end
  
  def show
  end
  
  def create
    inventory = Inventory.new(inventory_params)
    if inventory.save
      render json: inventory
    end
  end
  
  def update
    inventory = Inventory.find(params[:id])
    if inventory.update(inventory_params)
      render json: inventory
    end
  end
  
  def destroy
    if Inventory.find(params[:id]).destroy
      render json: { id: params[:id].to_i }
    end
  end
  
  private
    def inventory_params
      params.require(:inventory).permit(:item, :quantity, :wholesale_price, :retail_price)
    end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    client = Client.find(params[:client_id])
    orders = client.orders
    render json: orders
  end

  def create
    client = Client.find(params[:client_id])
    order = client.orders.new(order_params)
    if order.save
      render json: order
    end
  end

  private

  def order_params
    params.require(:order).permit(:product, :order_quantity, :date, :paid, :dollar_amount)
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  def index
  end

  def distance
    origin = params['origin']
    destination = params['destination']
    product_amount = params['productAmount'].to_i
    product_weight = params['productWeight'].to_i

    weight = product_amount * product_weight
    distance = GoogleDirections.new(origin, destination).distance_in_miles
    time = GoogleDirections.new(origin, destination).drive_time_in_minutes
    time = time.to_f / 60
    time = time / 24
    time = time + 3
    distance_cost = distance * 0.10
    weight_cost = weight * 0.20
    cost = distance_cost + weight_cost
    render json: {distance: distance, cost: cost.to_d, time: time.to_i}
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/about/index.html.erb
<div class="floating row container">
  <div>
    <img style="width: 200px; height: 200px; border-radius: 50%;" src="http://vignette3.wikia.nocookie.net/hanna-barbera/images/2/24/Johnny_Bravo.jpg/revision/latest?cb=20120423033926">
    <button class="btn grey lighten-3 red-text text-darken4" href="#">Github</button>
  </div>
</div>

app/views/clients/index.html.erb
<%= react_component 'Clients', {clients: @clients} %>

app/views/home/index.html.erb
<div class="container white-text center" style="margin-top: 5em;">
 <div class="row">
    <div class="col s12 m4">
      <div class="card red darken-4">
        <div class="card-image">
          <img src="http://m.searchpointer.com/a-r-chamber-bricks/images/brick_texture3325.jpg">
          <span class="shippingTracker">Shipping Calculator</span>
        </div>
        <div class="shipping calculator">
          <p>Use me to estimate shipping.</p>
        </div>
        <div class="card-action">
          <button class="btn grey lighten-3 red-text text-darken4"><%= link_to 'Shipments', shipments_path  %></button>
        </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card red darken-4">
        <div class="card-image">
          <img src="http://m.searchpointer.com/a-r-chamber-bricks/images/brick_texture3325.jpg">
          <span class="Inventory">Inventory</span>
        </div>
        <div class="inventory">
          <p>Check your inventory here.</p>
        </div>
        <div class="card-action">
          <button class="btn grey lighten-3 red-text text-darken4"><%= link_to 'Inventories', inventories_path  %></button>
        </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card red darken-4">
        <div class="card-image">
          <img src="http://m.searchpointer.com/a-r-chamber-bricks/images/brick_texture3325.jpg">
          <span class="shippingTracker">Client Tracker</span>
        </div>
        <div class="customer tracker">
          <p>Check all your customer info and orders here.</p>
        </div>
        <div class="card-action">
          <button class="btn grey lighten-3 red-text text-darken4"><%= link_to 'Clients', clients_path  %></button>
        </div>
      </div>
    </div>
 </div>
 <p>
   We are Brick n Morty, we have built some very functional and goodlooking small business tools for your use. Please feel free to contact us
   anywhere at any time a brickNmorty@gmail.com.
 </p>
</div>

app/views/inventories/index.html.erb
<%= react_component('Inventory', {inventories: @inventories}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrickNMortar</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

  <% if user_signed_in? %>
    <nav>
      <div class="nav-wrapper red darken-4" style="margin-bottom: 0;">
        <a href="#" class="brand-logo">Brick N Morty</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="/">Home</a></li>
          <li><a><%= link_to 'Logout', destroy_user_session_path, method: :delete %></a></li>
          <li><a href="/about">About Us</a></li>
          <!-- Dropdown Trigger -->
          <li>
            <a class='dropdown-button btn-med grey darken-3' href='#' data-activates='dropdown1'>Tools</a>
            <!-- Dropdown Structure -->
          </li>
            <ul id='dropdown1' class='dropdown-content'>
              <li><a href="/shipments" class="red-text text-lighten2">Shipping Calculator</a></li>
              <li><a href="inventories" class="red-text text-lighten2">Inventory</a></li>
              <li><a href="clients" class="red-text text-lighten2">Client Tracker</a></li>
            </ul>
        </ul>
      </div>
    </nav>
  <% else %>
    <nav>
      <div class="nav-wrapper red darken-4" style="margin-bottom: 0;">
        <a href="#" class="brand-logo">Brick N Morty</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="/">Home</a></li>
          <li><a href="/users/sign_in">Login</a></li>
          <li><a href="/users/sign_up">Signup</a></li>
          <li><a href="/about">About Us</a></li>
        </ul>
      </div>
    </nav>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/shipments/index.html.erb
<%= react_component('Shipment') %>